Repository ynput/ayon-unreal, pull requests merged in 2024-11, with the labels that each got.

#157 Backward compatibility for json layout without extension as data
  client/ayon_unreal/api/plugin.py
  client/ayon_unreal/plugins/load/load_layout.py
  client/ayon_unreal/plugins/load/load_layout_existing.py
Labels: type: bug

#155 Chore: Add action to upload to Ynput Cloud
  .github/workflows/upload_to_ynput_cloud.yml
Labels: type: maintenance

#160 Pre-launch hook for pyside installation
  client/ayon_unreal/hooks/pre_pyside_install.py
  client/ayon_unreal/lib.py
  client/ayon_unreal/ue_workers.py
  server/pre_launch_settings.py
  server/settings.py
Labels: type: bug, sponsored

#166 Implement function to get tracks for different UE version
  client/ayon_unreal/api/pipeline.py
  client/ayon_unreal/plugins/load/load_image_png.py
  client/ayon_unreal/plugins/load/load_layout.py
  client/ayon_unreal/plugins/load/load_layout_existing.py
  client/ayon_unreal/plugins/load/load_staticmesh_fbx.py
  client/ayon_unreal/plugins/publish/extract_camera.py
  client/ayon_unreal/plugins/publish/validate_camera_tracks.py
Labels: type: bug, type: maintenance

#171 Improve the order of the ayon plugins
  client/ayon_unreal/api/tools_ui.py
Labels: type: enhancement

#173 Emit action for building unreal workfile project preparation
  client/ayon_unreal/ue_workers.py
Labels: type: bug

#165 Farm rendering changes
  client/ayon_unreal/plugins/create/create_render.py
  client/ayon_unreal/plugins/publish/collect_render_files.py
  client/ayon_unreal/plugins/publish/collect_render_instances.py
  client/ayon_unreal/plugins/publish/create_farm_render_instances.py
  client/ayon_unreal/plugins/publish/switch_render_target.py
  package.py
Labels: type: bug
