Repository ynput/ayon-unreal, pull requests merged in 2024-10, with the labels that each got.

#92 Use extension from the json to define the asset extension to be loaded.
  client/ayon_unreal/plugins/load/load_layout.py
  server/settings.py
Labels: type: enhancement

#127 Update info in package.py
  package.py
Labels: type: maintenance

#72 Chore: Better ruff validation
  client/ayon_unreal/api/pipeline.py
  client/ayon_unreal/plugins/load/load_image_png.py
  client/ayon_unreal/plugins/load/load_skeletalmesh_fbx.py
  client/ayon_unreal/plugins/load/load_staticmesh_abc.py
  client/ayon_unreal/plugins/load/load_staticmesh_fbx.py
  client/ayon_unreal/plugins/publish/extract_fbx.py
  pyproject.toml
  ruff.toml
  server/import_settings.py
Labels: type: enhancement

#130 Use set range for setting up animation range for fbx animation import
  client/ayon_unreal/plugins/load/load_animation.py
Labels: type: bug

#39 Show dialog option working on other filetypes
  client/ayon_unreal/plugins/load/load_alembic_animation.py
  client/ayon_unreal/plugins/load/load_animation.py
  client/ayon_unreal/plugins/load/load_geometrycache_abc.py
  client/ayon_unreal/plugins/load/load_image_png.py
  client/ayon_unreal/plugins/load/load_skeletalmesh_abc.py
  client/ayon_unreal/plugins/load/load_skeletalmesh_fbx.py
  client/ayon_unreal/plugins/load/load_staticmesh_abc.py
  client/ayon_unreal/plugins/load/load_staticmesh_fbx.py
Labels: type: enhancement

#109 Aligning json data in published layout across DCCs
  client/ayon_unreal/plugins/load/load_layout.py
  client/ayon_unreal/plugins/publish/extract_layout.py
Labels: type: enhancement
