Repository ynput/ayon-unreal, pull requests merged in 2025-09, with the labels that each got.

#233 Feature: Look at project application variants for correct Unreal Engine executable first before deduction.
  client/ayon_unreal/lib.py
Labels: type: enhancement, community

#248 Use render presets on instance instead of settings values
  client/ayon_unreal/api/rendering.py
  client/ayon_unreal/plugins/create/create_render.py
  client/ayon_unreal/plugins/publish/create_farm_render_instances.py
Labels: type: enhancement

#250 Getting valid project settings during project creation
  client/ayon_unreal/lib.py
Labels: type: bug
